### ISSUE TITLE
缺少 requirements 依赖安装，无法直接项目无法复现

### ISSUE THREAD

**Issue by liury889** [pipixin321/HolmesVAD#1]
1.按照 readme 进行依赖安装，运行 demo or cli均出现 依赖包缺失的情况；

**Comment by pipixin321** [comment]
Thank you for your suggestion. Could you please specify the exact issues?

**Comment by liury889** [comment]
1.按照步骤安装完依赖，会报缺失“decord/opencv-python/pytorchvideo”包；详细如下：
1.1 ModuleNotFoundError: No module named 'pytorchvideo'；
1.2 ModuleNotFoundError: No module named 'cv2'
1.3 ModuleNotFoundError: No module named 'decord'

2.安装完第一步中缺失的依赖后runtimeerror；
RuntimeError: Internal: src/sentencepiece_processor.cc(1101) [model_proto->ParseFromArray(serialized.data(), serialized.size())


此外，能不能提供一个 demo 地址直接体验论文中实例

**Comment by liury889** [comment]
1.按照步骤安装完依赖，会报缺失“decord/opencv-python/pytorchvideo”包；详细如下：
1.1 ModuleNotFoundError: No module named 'pytorchvideo'；
1.2 ModuleNotFoundError: No module named 'cv2'
1.3 ModuleNotFoundError: No module named 'decord'

2.安装完第一步中缺失的依赖后runtimeerror；
RuntimeError: Internal: src/sentencepiece_processor.cc(1101) [model_proto->ParseFromArray(serialized.data(), serialized.size())


此外，能不能提供一个 demo 地址直接体验论文中实例

**Comment by pipixin321** [comment]
你好啊，
针对第一个问题，我们补充了依赖库安装说明；
我们复现时没有遇到你所说的问题，根据你的报错可能是tokenizer的问题，你可以检查一下transformer的版本是否和我们一致，或者下载的模型是否完整；
关于在线demo，我们目前还没有额外的计算资源去搭建；

**Comment by liury889** [comment]
> 1.按照步骤安装完依赖，会报缺失“decord/opencv-python/pytorchvideo”包；详细如下： 1.1 ModuleNotFoundError: No module named 'pytorchvideo'； 1.2 ModuleNotFoundError: No module named 'cv2' 1.3 ModuleNotFoundError: No module named 'decord'
> 
> 2.安装完第一步中缺失的依赖后runtimeerror； RuntimeError: Internal: src/sentencepiece_processor.cc(1101) [model_proto->ParseFromArray(serialized.data(), serialized.size())
> 
> 此外，能不能提供一个 demo 地址直接体验论文中实例

此项错误是使用 hf-cli 工具下载模型文件造成模型文件损坏造成的，采用 huggingface-cli 或者 python 代码下载使用国内镜像，错误消除
