### ISSUE TITLE
Temporal Sampler

### ISSUE THREAD

**Issue by tamirm2009** [pipixin321/HolmesVAD#10]
Hi, I saw the the video processor is always uniformly sample 8 frames in the raw video supplied by the user. But in the paper there is the UR-DMU Temporal Resampler, which chooses which frames to feed into the VLM. I don't see this functionality/module in the code, can you explain?

**Comment by pipixin321** [comment]
In the latest release of the inference code, the Temporal Sampler section is not yet included. However, it will be added in a future update. Please Stay tuned:)
