### ISSUE TITLE
VAD-Instruct50k数据集什么时候可以开源

### ISSUE THREAD

**Issue by Liu98C** [pipixin321/HolmesVAD#2]
您好，我非常喜欢贵团队的工作。请问VAD-Instruct50k数据集公开的时间确定了吗？是否可以创建一个微信群交流呢？

**Comment by pipixin321** [comment]
谢谢你的关注，我们已经公开了测试模型，由于部分视频涉及暴力，目前数据集还在进一步整理中，请持续关注~
