### ISSUE TITLE
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cuda:1! (when checking argument for argument index in method wrapper_CUDA__index_select)

### ISSUE THREAD

**Issue by Chenhaolin6** [pipixin321/HolmesVAD#3]
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cuda:1! (when checking argument for argument index in method wrapper_CUDA__index_select)
![image](https://github.com/pipixin321/HolmesVAD/assets/62549291/d5a627bc-9972-40e3-986f-8a0770cc2991)

**Comment by pipixin321** [comment]
Hello,
Did you specify the GPU when running the scripts, e.g., CUDA_VISIBLE_DEVICES=0?

**Comment by Chenhaolin6** [comment]
Using GPU 0 alone will result in graphics memory overflow.

**Comment by pipixin321** [comment]
You can add `--load-4bit` config if you don't have enough GPU memory, e.g., 
```bash
CUDA_VISIBLE_DEVICES=0 python demo/cli.py --model-path ./checkpoints/HolmesVAD-7B --file ./demo/examples/vad/RoadAccidents133_x264_270_451.mp4 --load-4bit
```
