### ISSUE TITLE
Request for Early Access to VAD-Instruct50k Dataset

### ISSUE THREAD

**Issue by irfanrah** [pipixin321/HolmesVAD#9]
Hello,

I noticed that the VAD-Instruct50k dataset is mentioned to be available soon, as per the repository's README:

> "Our VAD-Instruct50k will be available soon, welcome to star ⭐ this repository for the latest updates."

I would like to inquire if it would be possible to get early access to this dataset or if there is an estimated release date. This dataset is crucial for my ongoing research, and having access at the earliest would be greatly beneficial.

Thank you for your efforts in making these resources available to the community. I have starred the repository and am looking forward to the release.

**Comment by pipixin321** [comment]
Stay tuned for our latest work: [HolmesVAU](https://github.com/pipixin321/HolmesVAU), which is an upgraded version of Holmes-VAD, featuring improvements in annotation granularity, quantity, and quality, as well as utilizing a more powerful foundational MLLM model.
We have open sourced HIVAU-70k benchmarks and its raw annotation file. Please check.
